### ISSUE TITLE
targetSdkVersion 29 crashed

### ISSUE THREAD

**Issue by imneo** [TuSDK/TuSDK-for-Android#5]
java.lang.IllegalArgumentException: Invalid column COUNT(*) AS bucket_total
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
        at android.content.ContentResolver.query(ContentResolver.java:955)
        at android.content.ContentResolver.query(ContentResolver.java:891)
        at android.content.ContentResolver.query(ContentResolver.java:840)
        at org.lasque.tusdk.core.utils.sqllite.ImageSqlHelper.getWithCursorLoader(Unknown Source:14)
        at org.lasque.tusdk.core.utils.sqllite.ImageSqlHelper.getAlbumList(Unknown Source:22)
        at org.lasque.tusdk.geev2.impl.components.album.TuAlbumMultipleListFragment$1.run(Unknown Source:6)
        at java.lang.Thread.run(Thread.java:929)

**Comment by mhsnakdgn** [comment]
same problem! do you have any solution ?
